language:
    name: java
    version: 1.7
buildscript:
    name: maven
    version: 3
$archive:
    $cp:
        path: /export/pkgs/maven_acceptance_test
    $artifactory:
        url: https://artifactory.com
        accesskey: 1
postrun:
    prepend:
        $action1: action1_value
    append:
        $action2: action2_value
    define:
        $action3: action3_value
